"""Contrastive view generator for self-supervised learning.

The :class:`ContrastiveViewGenerator` produces two independently augmented
views of the same time-series window.  These views are consumed by the
NT-Xent loss during contrastive pre-training.

Each view is generated by applying an independently configured augmentation
pipeline, so the two views differ in their stochastic augmentations while
retaining the same underlying signal structure.

Example
-------
>>> import torch
>>> from src.data.view_generator import ContrastiveViewGenerator
>>> gen = ContrastiveViewGenerator()
>>> x = torch.randn(60, 10)          # (T, S)
>>> view1, view2 = gen(x)
>>> view1.shape, view2.shape
(torch.Size([60, 10]), torch.Size([60, 10]))

Batched input is also supported:

>>> x_batch = torch.randn(8, 60, 10) # (B, T, S)
>>> v1, v2 = gen(x_batch)
>>> v1.shape
torch.Size([8, 60, 10])
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import List, Optional, Tuple

import torch

from src.data.augmentations import (
    BaseAugmentation,
    Compose,
    ComposeConfig,
    GaussianNoise,
    GaussianNoiseConfig,
    Identity,
    IdentityConfig,
    RandomChannelMask,
    RandomChannelMaskConfig,
    RandomJitter,
    RandomJitterConfig,
    RandomScaling,
    RandomScalingConfig,
    RandomTimeMask,
    RandomTimeMaskConfig,
    RandomTimeShift,
    RandomTimeShiftConfig,
    _validate_tensor,
)

logger = logging.getLogger(__name__)


# ======================================================================
# Default pipeline factory
# ======================================================================


def _build_default_pipeline(seed_offset: int = 0) -> Compose:
    """Build the default augmentation pipeline for one view.

    The default pipeline applies the following augmentations, each
    with independent seeds (offset by *seed_offset* to keep the two
    views decorrelated):

    1. :class:`~src.data.augmentations.GaussianNoise` (p=0.8)
    2. :class:`~src.data.augmentations.RandomScaling` (p=0.8)
    3. :class:`~src.data.augmentations.RandomJitter` (p=0.5)
    4. :class:`~src.data.augmentations.RandomTimeMask` (p=0.5)
    5. :class:`~src.data.augmentations.RandomChannelMask` (p=0.3)
    6. :class:`~src.data.augmentations.RandomTimeShift` (p=0.5)

    Parameters
    ----------
    seed_offset : int
        Added to every augmentation seed so the two view pipelines
        sample different random values.

    Returns
    -------
    Compose
        Configured augmentation pipeline.
    """
    return Compose(
        augmentations=[
            GaussianNoise(GaussianNoiseConfig(std=0.05, p=0.8, seed=1 + seed_offset)),
            RandomScaling(
                RandomScalingConfig(scale_min=0.8, scale_max=1.2, p=0.8, seed=2 + seed_offset)
            ),
            RandomJitter(RandomJitterConfig(jitter_std=0.01, p=0.5, seed=3 + seed_offset)),
            RandomTimeMask(RandomTimeMaskConfig(mask_ratio=0.1, p=0.5, seed=4 + seed_offset)),
            RandomChannelMask(
                RandomChannelMaskConfig(mask_ratio=0.1, p=0.3, seed=5 + seed_offset)
            ),
            RandomTimeShift(RandomTimeShiftConfig(max_shift=5, p=0.5, seed=6 + seed_offset)),
        ],
        config=ComposeConfig(p=1.0),
    )


# ======================================================================
# Configuration
# ======================================================================


@dataclass
class ContrastiveViewGeneratorConfig:
    """Configuration for :class:`ContrastiveViewGenerator`.

    Parameters
    ----------
    seed : int or None
        Master random seed.  When set, both views are generated
        deterministically.  When *None*, views vary across calls.
    use_default_pipeline : bool
        If *True*, construct the default augmentation pipeline
        automatically.  Set to *False* when injecting custom pipelines
        via ``transform_1`` and ``transform_2``.
    """

    seed: Optional[int] = None
    use_default_pipeline: bool = True

    def __post_init__(self) -> None:
        if self.seed is not None and not isinstance(self.seed, int):
            raise TypeError(
                f"seed must be int or None, got {type(self.seed).__name__}"
            )


# ======================================================================
# View Generator
# ======================================================================


class ContrastiveViewGenerator:
    """Generate two independently augmented views of a time-series window.

    The two views are produced by applying *transform_1* and *transform_2*
    independently.  When *use_default_pipeline* is *True* in the config,
    two default pipelines are constructed with different seed offsets,
    ensuring independent stochasticity.

    Custom transforms can be injected for full flexibility (e.g., for
    ablation studies or dataset-specific augmentation strategies).

    Parameters
    ----------
    config : ContrastiveViewGeneratorConfig
        Generator configuration.
    transform_1 : BaseAugmentation or None
        Augmentation pipeline for view 1.  If *None*, a default pipeline
        is built (only when ``config.use_default_pipeline`` is *True*).
    transform_2 : BaseAugmentation or None
        Augmentation pipeline for view 2.  If *None*, a default pipeline
        is built (only when ``config.use_default_pipeline`` is *True*).

    Raises
    ------
    TypeError
        If *config* is not a :class:`ContrastiveViewGeneratorConfig`.
    ValueError
        If custom transforms are required but not provided.

    Example
    -------
    >>> import torch
    >>> from src.data.view_generator import ContrastiveViewGenerator
    >>> gen = ContrastiveViewGenerator()
    >>> x = torch.randn(60, 10)
    >>> v1, v2 = gen(x)
    >>> v1.shape == v2.shape == x.shape
    True
    """

    def __init__(
        self,
        config: ContrastiveViewGeneratorConfig = ContrastiveViewGeneratorConfig(),
        transform_1: Optional[BaseAugmentation] = None,
        transform_2: Optional[BaseAugmentation] = None,
    ) -> None:
        if not isinstance(config, ContrastiveViewGeneratorConfig):
            raise TypeError(
                f"config must be ContrastiveViewGeneratorConfig, "
                f"got {type(config).__name__}"
            )

        self._config = config

        # Resolve transform_1
        if transform_1 is not None:
            if not isinstance(transform_1, (BaseAugmentation, Compose)):
                raise TypeError(
                    f"transform_1 must be a BaseAugmentation or Compose, "
                    f"got {type(transform_1).__name__}"
                )
            self._transform_1 = transform_1
        elif config.use_default_pipeline:
            self._transform_1 = _build_default_pipeline(seed_offset=0)
        else:
            raise ValueError(
                "transform_1 must be provided when use_default_pipeline=False"
            )

        # Resolve transform_2
        if transform_2 is not None:
            if not isinstance(transform_2, (BaseAugmentation, Compose)):
                raise TypeError(
                    f"transform_2 must be a BaseAugmentation or Compose, "
                    f"got {type(transform_2).__name__}"
                )
            self._transform_2 = transform_2
        elif config.use_default_pipeline:
            # Offset seeds so view_2 differs from view_1
            self._transform_2 = _build_default_pipeline(seed_offset=100)
        else:
            raise ValueError(
                "transform_2 must be provided when use_default_pipeline=False"
            )

        logger.info(
            "ContrastiveViewGenerator initialised | seed=%s | "
            "use_default_pipeline=%s",
            config.seed,
            config.use_default_pipeline,
        )

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    @property
    def config(self) -> ContrastiveViewGeneratorConfig:
        """Return the generator configuration."""
        return self._config

    @property
    def transform_1(self) -> BaseAugmentation | Compose:
        """Return the augmentation pipeline for view 1."""
        return self._transform_1

    @property
    def transform_2(self) -> BaseAugmentation | Compose:
        """Return the augmentation pipeline for view 2."""
        return self._transform_2

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def __call__(
        self, x: torch.Tensor
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """Generate two independently augmented views.

        Parameters
        ----------
        x : torch.Tensor
            Time-series window of shape ``(T, S)`` or ``(B, T, S)``
            with a floating-point dtype; must not contain NaN or Inf.

        Returns
        -------
        tuple[torch.Tensor, torch.Tensor]
            ``(view_1, view_2)`` — both have the same shape as *x*.

        Raises
        ------
        TypeError
            If *x* is not a :class:`torch.Tensor`.
        ValueError
            If *x* fails validation.
        """
        _validate_tensor(x, "ContrastiveViewGenerator")

        logger.debug(
            "ContrastiveViewGenerator generating views | shape=%s | dtype=%s",
            tuple(x.shape),
            x.dtype,
        )

        if self._config.seed is not None:
            torch.manual_seed(self._config.seed)

        view_1 = self._transform_1(x)
        view_2 = self._transform_2(x)

        logger.debug(
            "ContrastiveViewGenerator views generated | "
            "view_1=%s | view_2=%s",
            tuple(view_1.shape),
            tuple(view_2.shape),
        )

        return view_1, view_2

    def generate(
        self, x: torch.Tensor
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """Alias for :meth:`__call__`.

        Parameters
        ----------
        x : torch.Tensor
            Time-series window.

        Returns
        -------
        tuple[torch.Tensor, torch.Tensor]
            ``(view_1, view_2)``.
        """
        return self(x)

    def __repr__(self) -> str:
        return (
            f"ContrastiveViewGenerator("
            f"seed={self._config.seed!r}, "
            f"transform_1={self._transform_1!r}, "
            f"transform_2={self._transform_2!r})"
        )
